package com.qifenqian.bms.accounting.accountMaintain.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.qifenqian.bms.accounting.accountMaintain.bean.BmsBaseBankAccount;
import com.qifenqian.bms.accounting.accountMaintain.bean.BmsBaseBankAccountExample;

@MapperScan
public interface BmsBaseBankAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int countByExample(BmsBaseBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int deleteByExample(BmsBaseBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int insert(BmsBaseBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int insertSelective(BmsBaseBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    List<BmsBaseBankAccount> selectByExample(BmsBaseBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    BmsBaseBankAccount selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") BmsBaseBankAccount record, @Param("example") BmsBaseBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int updateByExample(@Param("record") BmsBaseBankAccount record, @Param("example") BmsBaseBankAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int updateByPrimaryKeySelective(BmsBaseBankAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    int updateByPrimaryKey(BmsBaseBankAccount record);
    
    List<BmsBaseBankAccount> selectBaseBankAccountList(BmsBaseBankAccount record);
}