package com.qifenqian.bms.accounting.accountMaintain.bean;


/**
* 后台基础-银行账号表
*/
public class BmsBaseBankAccount {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.account_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 编号
	 */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.account_no
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 账号
	 */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.subject_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 科目编号
	 */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.account_name
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 账户名称
	 */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.curr_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 币别
	 */
    private String currCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.bank_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 所属银行(总行)
	 */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.bank_cnaps
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 所属开户行联行号
	 */
    private String bankCnaps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.status
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 状态：生效VALID/无效DISABLE
	 */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.memo
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 备注
	 */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.inst_user
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 初始写入人
	 */
    private String instUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.inst_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 初始写入时间
	 */
    private String instDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.lupd_user
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 最后更改人
	 */
    private String lupdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_base_bank_account.lupd_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
	/**
	 * 最后更改时间
	 */
    private String lupdDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.account_id
     *
     * @return the value of bms_base_bank_account.account_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.account_id
     *
     * @param accountId the value for bms_base_bank_account.account_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.account_no
     *
     * @return the value of bms_base_bank_account.account_no
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.account_no
     *
     * @param accountNo the value for bms_base_bank_account.account_no
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.subject_id
     *
     * @return the value of bms_base_bank_account.subject_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.subject_id
     *
     * @param subjectId the value for bms_base_bank_account.subject_id
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.account_name
     *
     * @return the value of bms_base_bank_account.account_name
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.account_name
     *
     * @param accountName the value for bms_base_bank_account.account_name
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.curr_code
     *
     * @return the value of bms_base_bank_account.curr_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getCurrCode() {
        return currCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.curr_code
     *
     * @param currCode the value for bms_base_bank_account.curr_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setCurrCode(String currCode) {
        this.currCode = currCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.bank_code
     *
     * @return the value of bms_base_bank_account.bank_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.bank_code
     *
     * @param bankCode the value for bms_base_bank_account.bank_code
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.bank_cnaps
     *
     * @return the value of bms_base_bank_account.bank_cnaps
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getBankCnaps() {
        return bankCnaps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.bank_cnaps
     *
     * @param bankCnaps the value for bms_base_bank_account.bank_cnaps
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setBankCnaps(String bankCnaps) {
        this.bankCnaps = bankCnaps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.status
     *
     * @return the value of bms_base_bank_account.status
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.status
     *
     * @param status the value for bms_base_bank_account.status
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.memo
     *
     * @return the value of bms_base_bank_account.memo
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.memo
     *
     * @param memo the value for bms_base_bank_account.memo
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.inst_user
     *
     * @return the value of bms_base_bank_account.inst_user
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.inst_datetime
     *
     * @return the value of bms_base_bank_account.inst_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    

    public String getInstUser() {
		return instUser;
	}

	public void setInstUser(String instUser) {
		this.instUser = instUser;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.inst_datetime
     *
     * @param instDatetime the value for bms_base_bank_account.inst_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.lupd_user
     *
     * @return the value of bms_base_bank_account.lupd_user
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_base_bank_account.lupd_datetime
     *
     * @return the value of bms_base_bank_account.lupd_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */



	public String getLupdUser() {
		return lupdUser;
	}

	public void setLupdUser(String lupdUser) {
		this.lupdUser = lupdUser;
	}

	public String getInstDatetime() {
		return instDatetime;
	}

	public String getLupdDatetime() {
		return lupdDatetime;
	}

	public void setInstDatetime(String instDatetime) {
		this.instDatetime = instDatetime;
	}

	public void setLupdDatetime(String lupdDatetime) {
		this.lupdDatetime = lupdDatetime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_base_bank_account.lupd_datetime
     *
     * @param lupdDatetime the value for bms_base_bank_account.lupd_datetime
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
   
}
