package com.qifenqian.bms.accounting.accountMaintain.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BmsBaseBankAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public BmsBaseBankAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNull() {
            addCriterion("account_no is null");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNotNull() {
            addCriterion("account_no is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNoEqualTo(String value) {
            addCriterion("account_no =", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotEqualTo(String value) {
            addCriterion("account_no <>", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThan(String value) {
            addCriterion("account_no >", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("account_no >=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThan(String value) {
            addCriterion("account_no <", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThanOrEqualTo(String value) {
            addCriterion("account_no <=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLike(String value) {
            addCriterion("account_no like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotLike(String value) {
            addCriterion("account_no not like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoIn(List<String> values) {
            addCriterion("account_no in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotIn(List<String> values) {
            addCriterion("account_no not in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoBetween(String value1, String value2) {
            addCriterion("account_no between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotBetween(String value1, String value2) {
            addCriterion("account_no not between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNull() {
            addCriterion("account_name is null");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNotNull() {
            addCriterion("account_name is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNameEqualTo(String value) {
            addCriterion("account_name =", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotEqualTo(String value) {
            addCriterion("account_name <>", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThan(String value) {
            addCriterion("account_name >", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("account_name >=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThan(String value) {
            addCriterion("account_name <", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThanOrEqualTo(String value) {
            addCriterion("account_name <=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLike(String value) {
            addCriterion("account_name like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotLike(String value) {
            addCriterion("account_name not like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameIn(List<String> values) {
            addCriterion("account_name in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotIn(List<String> values) {
            addCriterion("account_name not in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameBetween(String value1, String value2) {
            addCriterion("account_name between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotBetween(String value1, String value2) {
            addCriterion("account_name not between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andCurrCodeIsNull() {
            addCriterion("curr_code is null");
            return (Criteria) this;
        }

        public Criteria andCurrCodeIsNotNull() {
            addCriterion("curr_code is not null");
            return (Criteria) this;
        }

        public Criteria andCurrCodeEqualTo(String value) {
            addCriterion("curr_code =", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeNotEqualTo(String value) {
            addCriterion("curr_code <>", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeGreaterThan(String value) {
            addCriterion("curr_code >", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("curr_code >=", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeLessThan(String value) {
            addCriterion("curr_code <", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeLessThanOrEqualTo(String value) {
            addCriterion("curr_code <=", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeLike(String value) {
            addCriterion("curr_code like", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeNotLike(String value) {
            addCriterion("curr_code not like", value, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeIn(List<String> values) {
            addCriterion("curr_code in", values, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeNotIn(List<String> values) {
            addCriterion("curr_code not in", values, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeBetween(String value1, String value2) {
            addCriterion("curr_code between", value1, value2, "currCode");
            return (Criteria) this;
        }

        public Criteria andCurrCodeNotBetween(String value1, String value2) {
            addCriterion("curr_code not between", value1, value2, "currCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNull() {
            addCriterion("bank_code is null");
            return (Criteria) this;
        }

        public Criteria andBankCodeIsNotNull() {
            addCriterion("bank_code is not null");
            return (Criteria) this;
        }

        public Criteria andBankCodeEqualTo(String value) {
            addCriterion("bank_code =", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotEqualTo(String value) {
            addCriterion("bank_code <>", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThan(String value) {
            addCriterion("bank_code >", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_code >=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThan(String value) {
            addCriterion("bank_code <", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLessThanOrEqualTo(String value) {
            addCriterion("bank_code <=", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeLike(String value) {
            addCriterion("bank_code like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotLike(String value) {
            addCriterion("bank_code not like", value, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeIn(List<String> values) {
            addCriterion("bank_code in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotIn(List<String> values) {
            addCriterion("bank_code not in", values, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeBetween(String value1, String value2) {
            addCriterion("bank_code between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCodeNotBetween(String value1, String value2) {
            addCriterion("bank_code not between", value1, value2, "bankCode");
            return (Criteria) this;
        }

        public Criteria andBankCnapsIsNull() {
            addCriterion("bank_cnaps is null");
            return (Criteria) this;
        }

        public Criteria andBankCnapsIsNotNull() {
            addCriterion("bank_cnaps is not null");
            return (Criteria) this;
        }

        public Criteria andBankCnapsEqualTo(String value) {
            addCriterion("bank_cnaps =", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsNotEqualTo(String value) {
            addCriterion("bank_cnaps <>", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsGreaterThan(String value) {
            addCriterion("bank_cnaps >", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsGreaterThanOrEqualTo(String value) {
            addCriterion("bank_cnaps >=", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsLessThan(String value) {
            addCriterion("bank_cnaps <", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsLessThanOrEqualTo(String value) {
            addCriterion("bank_cnaps <=", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsLike(String value) {
            addCriterion("bank_cnaps like", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsNotLike(String value) {
            addCriterion("bank_cnaps not like", value, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsIn(List<String> values) {
            addCriterion("bank_cnaps in", values, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsNotIn(List<String> values) {
            addCriterion("bank_cnaps not in", values, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsBetween(String value1, String value2) {
            addCriterion("bank_cnaps between", value1, value2, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andBankCnapsNotBetween(String value1, String value2) {
            addCriterion("bank_cnaps not between", value1, value2, "bankCnaps");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNull() {
            addCriterion("inst_user is null");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNotNull() {
            addCriterion("inst_user is not null");
            return (Criteria) this;
        }

        public Criteria andInstUserEqualTo(Integer value) {
            addCriterion("inst_user =", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotEqualTo(Integer value) {
            addCriterion("inst_user <>", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThan(Integer value) {
            addCriterion("inst_user >", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("inst_user >=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThan(Integer value) {
            addCriterion("inst_user <", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThanOrEqualTo(Integer value) {
            addCriterion("inst_user <=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserIn(List<Integer> values) {
            addCriterion("inst_user in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotIn(List<Integer> values) {
            addCriterion("inst_user not in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserBetween(Integer value1, Integer value2) {
            addCriterion("inst_user between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotBetween(Integer value1, Integer value2) {
            addCriterion("inst_user not between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNull() {
            addCriterion("inst_datetime is null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNotNull() {
            addCriterion("inst_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeEqualTo(Date value) {
            addCriterion("inst_datetime =", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotEqualTo(Date value) {
            addCriterion("inst_datetime <>", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThan(Date value) {
            addCriterion("inst_datetime >", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("inst_datetime >=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThan(Date value) {
            addCriterion("inst_datetime <", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("inst_datetime <=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIn(List<Date> values) {
            addCriterion("inst_datetime in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotIn(List<Date> values) {
            addCriterion("inst_datetime not in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeBetween(Date value1, Date value2) {
            addCriterion("inst_datetime between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("inst_datetime not between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNull() {
            addCriterion("lupd_user is null");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNotNull() {
            addCriterion("lupd_user is not null");
            return (Criteria) this;
        }

        public Criteria andLupdUserEqualTo(Integer value) {
            addCriterion("lupd_user =", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotEqualTo(Integer value) {
            addCriterion("lupd_user <>", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThan(Integer value) {
            addCriterion("lupd_user >", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("lupd_user >=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThan(Integer value) {
            addCriterion("lupd_user <", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThanOrEqualTo(Integer value) {
            addCriterion("lupd_user <=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserIn(List<Integer> values) {
            addCriterion("lupd_user in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotIn(List<Integer> values) {
            addCriterion("lupd_user not in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserBetween(Integer value1, Integer value2) {
            addCriterion("lupd_user between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotBetween(Integer value1, Integer value2) {
            addCriterion("lupd_user not between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNull() {
            addCriterion("lupd_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNotNull() {
            addCriterion("lupd_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeEqualTo(Date value) {
            addCriterion("lupd_datetime =", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotEqualTo(Date value) {
            addCriterion("lupd_datetime <>", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThan(Date value) {
            addCriterion("lupd_datetime >", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime >=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThan(Date value) {
            addCriterion("lupd_datetime <", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime <=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIn(List<Date> values) {
            addCriterion("lupd_datetime in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotIn(List<Date> values) {
            addCriterion("lupd_datetime not in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime not between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 15 10:01:08 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bms_base_bank_account
     *
     * @mbggenerated Tue Mar 15 10:01:08 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}