package com.qifenqian.bms.meeting.winShow.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.qifenqian.bms.meeting.winShow.bean.BasePrizeWin;
import com.qifenqian.bms.meeting.winShow.bean.BasePrizeWinExample;

@MapperScan
public interface BasePrizeWinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int countByExample(BasePrizeWinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int deleteByExample(BasePrizeWinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int deleteByPrimaryKey(Integer winId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int insert(BasePrizeWin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int insertSelective(BasePrizeWin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    List<BasePrizeWin> selectByExample(BasePrizeWinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    BasePrizeWin selectByPrimaryKey(Integer winId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") BasePrizeWin record, @Param("example") BasePrizeWinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int updateByExample(@Param("record") BasePrizeWin record, @Param("example") BasePrizeWinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int updateByPrimaryKeySelective(BasePrizeWin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    int updateByPrimaryKey(BasePrizeWin record);
    
    List<BasePrizeWin>  showPrizeWinNow(@Param("prizeId") String prizeId);
}