server:
   port: 8083
spring:
   profiles:
      active: '@spring.profiles.active@'
   mvc:
      view:
         prefix: /views/
         suffix: .jsp
   application:
      name: bms
servlet:
   multipart:
      max-file-size: 10MB
      max-request-size: 10MB