package com.qifenqian.bms.basemanager.trade.bean;



import java.util.Date;

/**
 * TdTradeBillMain generated by hbm2java
 */
public class AllTradeBill {
	private String orderId;
	private String mchId;
	private String mchName;
	private String service;
	private String channel;
	private String channelSub;
	private String zxOrderId;
	private String channelOrderId;
	private String pgURL;
	private String bgURL;
	private String version;
	
	private String orderAmt;
	private String tradeAmt;
	private String couponAmt;
	private String prodDesc;
	private String payType;
	private String orderTimeStamp;
	private Integer orderTimeOut;
	private String orderExpire;
	private String extDate1;
	private String extDate2;
	private String orderState;
	private Date notifyTime;
	private String notifyCount;
	private String notifyResult;
	private Date createTime;
	private Date finishTime;
	private Date refundTime;
	private Date modifyTime;
	private String modifyId;
	public String getOrderId() {
		return orderId;
	}
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}
	public String getMchId() {
		return mchId;
	}
	public void setMchId(String mchId) {
		this.mchId = mchId;
	}
	public String getMchName() {
		return mchName;
	}
	public void setMchName(String mchName) {
		this.mchName = mchName;
	}
	public String getService() {
		return service;
	}
	public void setService(String service) {
		this.service = service;
	}
	public String getChannel() {
		return channel;
	}
	public void setChannel(String channel) {
		this.channel = channel;
	}
	public String getChannelSub() {
		return channelSub;
	}
	public void setChannelSub(String channelSub) {
		this.channelSub = channelSub;
	}
	public String getZxOrderId() {
		return zxOrderId;
	}
	public void setZxOrderId(String zxOrderId) {
		this.zxOrderId = zxOrderId;
	}
	public String getChannelOrderId() {
		return channelOrderId;
	}
	public void setChannelOrderId(String channelOrderId) {
		this.channelOrderId = channelOrderId;
	}
	public String getPgURL() {
		return pgURL;
	}
	public void setPgURL(String pgURL) {
		this.pgURL = pgURL;
	}
	public String getBgURL() {
		return bgURL;
	}
	public void setBgURL(String bgURL) {
		this.bgURL = bgURL;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
	}
	public String getOrderTimeStamp() {
		return orderTimeStamp;
	}
	public void setOrderTimeStamp(String orderTimeStamp) {
		this.orderTimeStamp = orderTimeStamp;
	}
	public String getOrderAmt() {
		return orderAmt;
	}
	public void setOrderAmt(String orderAmt) {
		this.orderAmt = orderAmt;
	}
	
	public String getTradeAmt() {
		return tradeAmt;
	}
	public void setTradeAmt(String tradeAmt) {
		this.tradeAmt = tradeAmt;
	}
	public String getCouponAmt() {
		return couponAmt;
	}
	public void setCouponAmt(String couponAmt) {
		this.couponAmt = couponAmt;
	}
	public String getProdDesc() {
		return prodDesc;
	}
	public void setProdDesc(String prodDesc) {
		this.prodDesc = prodDesc;
	}
	public String getPayType() {
		return payType;
	}
	public void setPayType(String payType) {
		this.payType = payType;
	}
	public Integer getOrderTimeOut() {
		return orderTimeOut;
	}
	public void setOrderTimeOut(Integer orderTimeOut) {
		this.orderTimeOut = orderTimeOut;
	}
	public String getOrderExpire() {
		return orderExpire;
	}
	public void setOrderExpire(String orderExpire) {
		this.orderExpire = orderExpire;
	}
	public String getExtDate1() {
		return extDate1;
	}
	public void setExtDate1(String extDate1) {
		this.extDate1 = extDate1;
	}
	public String getExtDate2() {
		return extDate2;
	}
	public void setExtDate2(String extDate2) {
		this.extDate2 = extDate2;
	}
	public String getOrderState() {
		return orderState;
	}
	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}
	public Date getNotifyTime() {
		return notifyTime;
	}
	public void setNotifyTime(Date notifyTime) {
		this.notifyTime = notifyTime;
	}
	public String getNotifyCount() {
		return notifyCount;
	}
	public void setNotifyCount(String notifyCount) {
		this.notifyCount = notifyCount;
	}
	public String getNotifyResult() {
		return notifyResult;
	}
	public void setNotifyResult(String notifyResult) {
		this.notifyResult = notifyResult;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getFinishTime() {
		return finishTime;
	}
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}
	public Date getRefundTime() {
		return refundTime;
	}
	public void setRefundTime(Date refundTime) {
		this.refundTime = refundTime;
	}
	public Date getModifyTime() {
		return modifyTime;
	}
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
	public String getModifyId() {
		return modifyId;
	}
	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}
	
}
