package com.qifenqian.bms.basemanager.trade.bean;



import java.math.BigDecimal;
import java.util.Date;

/**
 * TdTradeBillMain generated by hbm2java
 */
public class TdTradeBillMain {

	/** 
	 * 订单号.
	 */
	private String orderId;

	/** 
	 * 订单生成时间.
	 */
	private Date orderCreateTime;
	
	/**
	 * 订单完成时间
	 */
	private Date orderCoreReturnTime;

	/** 
	 * 订单名称.
	 */
	private String orderName;

	/** 
	 * 交易类型：
	           1001 转账到7分钱；
	           1002 转账到银行卡；
	           1101 商户接入-收款-无担保；
	           1102 商户接入-收款-有担保；
	           1201 转入7分宝；
	           1202 转出7分宝；
	           8001 退款。.
	 */
	private String tradeType;

	/** 
	 * 订单描述.
	 */
	private String orderDesc;

	/** 
	 * 01：待提交；02 提交核心处理；03核心已受理；04 核心返回失败；00 核心返回成功；99 取消.
	 */
	private String orderState;

	/** 
	 * 核心返回码.
	 */
	private String orderCoreReturnCode;

	/** 
	 * 核心返回信息.
	 */
	private String orderCoreReturnMsg;

	/** 
	 * 发起方客户编号.
	 */
	private String srcCustId;

	/** 
	 * 付方是否平台客户：1是，0否。.
	 */
	private String payerIsPlatformCust;

	/** 
	 * 付方客户编号.
	 */
	private String payerCustId;

	/** 
	 * 付方账户类型：SEVN_CUS_0 七分钱账户；QFB0_CUS_0 七分宝账户；.
	 */
	private String payerAcctType;

	/** 
	 * 付方客户名.
	 */
	private String payerCustName;

	/** 
	 * 总金额.
	 */
	private BigDecimal sumAmt;

	/** 
	 * 币别.
	 */
	private String currCode;

	/** 
	 * 是否需要充值：1是，0否，2：不确定.
	 */
	private String isNeedCharge;

	/** 
	 * 充值流水号.
	 */
	private String chargeSn;

	/** 
	 * 需充值的客户编号.
	 */
	private String chargeCustId;

	/** 
	 * 需充值的账户类型：只能充七分钱.
	 */
	private String chargeAcctType;

	/** 
	 * 充值方式：1快捷支付（已开通）；2快捷支付（未开通）；3网银.
	 */
	private String chargeType;

	/** 
	 * 充值行别.
	 */
	private String chargeBankType;

	/** 
	 * 充值行号 支付系统行号.
	 */
	private String chargeBankCode;

	/** 
	 * 充值开户行行名.
	 */
	private String chargeBankName;

	/** 
	 * 充值银行卡类型：1：借记卡；2：信用卡.
	 */
	private String chargeBankCardType;

	/** 
	 * 充值银行卡号.
	 */
	private String chargeBankCardNo;

	/** 
	 * 对于未开通快捷支付的，此状态用于记录与核心的开通交互情况：1请求发往核心；2核心返回失败；0核心返回成功.
	 */
	private String fastPayOpenState;

	/** 
	 * 充值银行账号（内部ID），快捷支付才有.
	 */
	private String chargeBankCardNoInternal;

	/** 
	 * 充值币别.
	 */
	private String chargeCurrCode;

	/** 
	 * 充值金额.
	 */
	private BigDecimal chargeAmt;

	/** 
	 * 01 待支付；02 网银返回成功；03 网银返回失败；04：提交核心处理；05 核心返回失败；00 充值成功.
	 */
	private String chargeNetpayState;

	/** 
	 * 收方是否平台客户：1是，0否。.
	 */
	private String payeeIsPlatformCust;

	/** 
	 * 收方客户编号.
	 */
	private String payeeCustId;

	/** 
	 * 收方账户类型：BANK_CUS_0  银行借记账户；BANK_CUS_1 银行贷记账户；SEVN_CUS_0 七分钱账户；QFB0_CUS_0 七分宝账户；.
	 */
	private String payeeAcctType;

	/** 
	 * 收方客户名.
	 */
	private String payeeCustName;

	/** 
	 * 收方行别.
	 */
	private String payeeBankType;

	/** 
	 * 行号 支付系统行号.
	 */
	private String payeeBankCode;

	/** 
	 * 开户行行名.
	 */
	private String payeeBankName;

	/** 
	 * 开户行地区代码.
	 */
	private String payeeBankArea;

	/** 
	 * 收方银行账号.
	 */
	private String payeeBankAcctNo;

	/** 
	 * 收方姓名.
	 */
	private String payeeBankAcctName;

	/** 
	 * 紧急程度：对于转账交易：1：2小时到账；2：24小时内到账.
	 */
	private String emergencyDegree;

	/** 
	 * 是否担保交易：1是，0否.
	 */
	private String isGuarantee;

	/** 
	 * 担保交易状态：1核心未冻结货款；2核心已冻结货款；3买家确认收货，通知核心打款给卖家；4核心打款成功，卖家收到了货款.
	 */
	private String guaranteeState;

	/** 
	 * 核心返回码.
	 */
	private String guaranteeCoreReturnCode;

	/** 
	 * 核心返回信息.
	 */
	private String guaranteeCoreReturnMsg;

	/** 
	 * 操作终端：P：PC端；M：移动手机端.
	 */
	private String opTerm;

	/** 
	 * 返回商家页面地址.
	 */
	private String pgUrl;

	/** 
	 * 通知商家后台调用地址.
	 */
	private String bgUrl;

	/** 
	 * 退款关联订单号（退款交易时有值）.
	 */
	private String drawbackOrderId;

	/** 
	 * 创建人.
	 */
	private String createId;

	/** 
	 * 创建时间.
	 */
	private Date createTime;

	/** 
	 * 修改人.
	 */
	private String modifyId;

	/** 
	 * 修改时间.
	 */
	private Date modifyTime;
	
	/**
	 * 核心返回流水号
	 */
	private String coreSn;
	
	/**
	 * 付方账户ID
	 */
	private String payerAcctId;
	
	/**
	 * 收方账户ID
	 */
	private String payeeAcctId;

	public TdTradeBillMain() {
	}

	public TdTradeBillMain(String orderId, Date orderCreateTime,
			String orderName, String tradeType, String orderState,
			String srcCustId, String payerIsPlatformCust, String payerCustId,
			String payerAcctType, String payerCustName, BigDecimal sumAmt,
			String currCode, String isNeedCharge, String payeeIsPlatformCust,
			String opTerm, Date createTime, Date modifyTime, String payerAcctId) {
		this.orderId = orderId;
		this.orderCreateTime = orderCreateTime;
		this.orderName = orderName;
		this.tradeType = tradeType;
		this.orderState = orderState;
		this.srcCustId = srcCustId;
		this.payerIsPlatformCust = payerIsPlatformCust;
		this.payerCustId = payerCustId;
		this.payerAcctType = payerAcctType;
		this.payerCustName = payerCustName;
		this.sumAmt = sumAmt;
		this.currCode = currCode;
		this.isNeedCharge = isNeedCharge;
		this.payeeIsPlatformCust = payeeIsPlatformCust;
		this.opTerm = opTerm;
		this.createTime = createTime;
		this.modifyTime = modifyTime;
		this.payerAcctId = payerAcctId;
	}

	public TdTradeBillMain(String orderId, Date orderCreateTime,
			String orderName, String tradeType, String orderDesc,
			String orderState, String orderCoreReturnCode,
			String orderCoreReturnMsg, String srcCustId,
			String payerIsPlatformCust, String payerCustId,
			String payerAcctType, String payerCustName, BigDecimal sumAmt,
			String currCode, String isNeedCharge, String chargeSn,
			String chargeCustId, String chargeAcctType, String chargeType,
			String chargeBankType, String chargeBankCode,
			String chargeBankName, String chargeBankCardType,
			String chargeBankCardNo, String fastPayOpenState,
			String chargeBankCardNoInternal, String chargeCurrCode,
			BigDecimal chargeAmt, String chargeNetpayState,
			String payeeIsPlatformCust, String payeeCustId,
			String payeeAcctType, String payeeCustName, String payeeBankType,
			String payeeBankCode, String payeeBankName, String payeeBankArea,
			String payeeBankAcctNo, String payeeBankAcctName,
			String emergencyDegree, String isGuarantee, String guaranteeState,
			String guaranteeCoreReturnCode, String guaranteeCoreReturnMsg,
			String opTerm, String pgUrl, String bgUrl, String drawbackOrderId,
			String createId, Date createTime, String modifyId, Date modifyTime, 
			String coreSn, String payerAcctId, String payeeAcctId) {
		this.orderId = orderId;
		this.orderCreateTime = orderCreateTime;
		this.orderName = orderName;
		this.tradeType = tradeType;
		this.orderDesc = orderDesc;
		this.orderState = orderState;
		this.orderCoreReturnCode = orderCoreReturnCode;
		this.orderCoreReturnMsg = orderCoreReturnMsg;
		this.srcCustId = srcCustId;
		this.payerIsPlatformCust = payerIsPlatformCust;
		this.payerCustId = payerCustId;
		this.payerAcctType = payerAcctType;
		this.payerCustName = payerCustName;
		this.sumAmt = sumAmt;
		this.currCode = currCode;
		this.isNeedCharge = isNeedCharge;
		this.chargeSn = chargeSn;
		this.chargeCustId = chargeCustId;
		this.chargeAcctType = chargeAcctType;
		this.chargeType = chargeType;
		this.chargeBankType = chargeBankType;
		this.chargeBankCode = chargeBankCode;
		this.chargeBankName = chargeBankName;
		this.chargeBankCardType = chargeBankCardType;
		this.chargeBankCardNo = chargeBankCardNo;
		this.fastPayOpenState = fastPayOpenState;
		this.chargeBankCardNoInternal = chargeBankCardNoInternal;
		this.chargeCurrCode = chargeCurrCode;
		this.chargeAmt = chargeAmt;
		this.chargeNetpayState = chargeNetpayState;
		this.payeeIsPlatformCust = payeeIsPlatformCust;
		this.payeeCustId = payeeCustId;
		this.payeeAcctType = payeeAcctType;
		this.payeeCustName = payeeCustName;
		this.payeeBankType = payeeBankType;
		this.payeeBankCode = payeeBankCode;
		this.payeeBankName = payeeBankName;
		this.payeeBankArea = payeeBankArea;
		this.payeeBankAcctNo = payeeBankAcctNo;
		this.payeeBankAcctName = payeeBankAcctName;
		this.emergencyDegree = emergencyDegree;
		this.isGuarantee = isGuarantee;
		this.guaranteeState = guaranteeState;
		this.guaranteeCoreReturnCode = guaranteeCoreReturnCode;
		this.guaranteeCoreReturnMsg = guaranteeCoreReturnMsg;
		this.opTerm = opTerm;
		this.pgUrl = pgUrl;
		this.bgUrl = bgUrl;
		this.drawbackOrderId = drawbackOrderId;
		this.createId = createId;
		this.createTime = createTime;
		this.modifyId = modifyId;
		this.modifyTime = modifyTime;
		this.coreSn = coreSn;
		this.payerAcctId = payerAcctId;
		this.payeeAcctId = payeeAcctId;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Date getOrderCreateTime() {
		return this.orderCreateTime;
	}

	public void setOrderCreateTime(Date orderCreateTime) {
		this.orderCreateTime = orderCreateTime;
	}
	public Date getOrderCoreReturnTime() {
		return orderCoreReturnTime;
	}

	public void setOrderCoreReturnTime(Date orderCoreReturnTime) {
		this.orderCoreReturnTime = orderCoreReturnTime;
	}
	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public String getTradeType() {
		return this.tradeType;
	}

	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	public String getOrderDesc() {
		return this.orderDesc;
	}

	public void setOrderDesc(String orderDesc) {
		this.orderDesc = orderDesc;
	}

	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	public String getOrderCoreReturnCode() {
		return this.orderCoreReturnCode;
	}

	public void setOrderCoreReturnCode(String orderCoreReturnCode) {
		this.orderCoreReturnCode = orderCoreReturnCode;
	}

	public String getOrderCoreReturnMsg() {
		return this.orderCoreReturnMsg;
	}

	public void setOrderCoreReturnMsg(String orderCoreReturnMsg) {
		this.orderCoreReturnMsg = orderCoreReturnMsg;
	}

	public String getSrcCustId() {
		return this.srcCustId;
	}

	public void setSrcCustId(String srcCustId) {
		this.srcCustId = srcCustId;
	}

	public String getPayerIsPlatformCust() {
		return this.payerIsPlatformCust;
	}

	public void setPayerIsPlatformCust(String payerIsPlatformCust) {
		this.payerIsPlatformCust = payerIsPlatformCust;
	}

	public String getPayerCustId() {
		return this.payerCustId;
	}

	public void setPayerCustId(String payerCustId) {
		this.payerCustId = payerCustId;
	}

	public String getPayerAcctType() {
		return this.payerAcctType;
	}

	public void setPayerAcctType(String payerAcctType) {
		this.payerAcctType = payerAcctType;
	}

	public String getPayerCustName() {
		return this.payerCustName;
	}

	public void setPayerCustName(String payerCustName) {
		this.payerCustName = payerCustName;
	}

	public BigDecimal getSumAmt() {
		return this.sumAmt;
	}

	public void setSumAmt(BigDecimal sumAmt) {
		this.sumAmt = sumAmt;
	}

	public String getCurrCode() {
		return this.currCode;
	}

	public void setCurrCode(String currCode) {
		this.currCode = currCode;
	}

	public String getIsNeedCharge() {
		return this.isNeedCharge;
	}

	public void setIsNeedCharge(String isNeedCharge) {
		this.isNeedCharge = isNeedCharge;
	}

	public String getChargeSn() {
		return this.chargeSn;
	}

	public void setChargeSn(String chargeSn) {
		this.chargeSn = chargeSn;
	}

	public String getChargeCustId() {
		return this.chargeCustId;
	}

	public void setChargeCustId(String chargeCustId) {
		this.chargeCustId = chargeCustId;
	}

	public String getChargeAcctType() {
		return this.chargeAcctType;
	}

	public void setChargeAcctType(String chargeAcctType) {
		this.chargeAcctType = chargeAcctType;
	}

	public String getChargeType() {
		return this.chargeType;
	}

	public void setChargeType(String chargeType) {
		this.chargeType = chargeType;
	}

	public String getChargeBankType() {
		return this.chargeBankType;
	}

	public void setChargeBankType(String chargeBankType) {
		this.chargeBankType = chargeBankType;
	}

	public String getChargeBankCode() {
		return this.chargeBankCode;
	}

	public void setChargeBankCode(String chargeBankCode) {
		this.chargeBankCode = chargeBankCode;
	}

	public String getChargeBankName() {
		return this.chargeBankName;
	}

	public void setChargeBankName(String chargeBankName) {
		this.chargeBankName = chargeBankName;
	}

	public String getChargeBankCardType() {
		return this.chargeBankCardType;
	}

	public void setChargeBankCardType(String chargeBankCardType) {
		this.chargeBankCardType = chargeBankCardType;
	}

	public String getChargeBankCardNo() {
		return this.chargeBankCardNo;
	}

	public void setChargeBankCardNo(String chargeBankCardNo) {
		this.chargeBankCardNo = chargeBankCardNo;
	}

	public String getFastPayOpenState() {
		return this.fastPayOpenState;
	}

	public void setFastPayOpenState(String fastPayOpenState) {
		this.fastPayOpenState = fastPayOpenState;
	}

	public String getChargeBankCardNoInternal() {
		return this.chargeBankCardNoInternal;
	}

	public void setChargeBankCardNoInternal(String chargeBankCardNoInternal) {
		this.chargeBankCardNoInternal = chargeBankCardNoInternal;
	}

	public String getChargeCurrCode() {
		return this.chargeCurrCode;
	}

	public void setChargeCurrCode(String chargeCurrCode) {
		this.chargeCurrCode = chargeCurrCode;
	}

	public BigDecimal getChargeAmt() {
		return this.chargeAmt;
	}

	public void setChargeAmt(BigDecimal chargeAmt) {
		this.chargeAmt = chargeAmt;
	}

	public String getChargeNetpayState() {
		return this.chargeNetpayState;
	}

	public void setChargeNetpayState(String chargeNetpayState) {
		this.chargeNetpayState = chargeNetpayState;
	}

	public String getPayeeIsPlatformCust() {
		return this.payeeIsPlatformCust;
	}

	public void setPayeeIsPlatformCust(String payeeIsPlatformCust) {
		this.payeeIsPlatformCust = payeeIsPlatformCust;
	}

	public String getPayeeCustId() {
		return this.payeeCustId;
	}

	public void setPayeeCustId(String payeeCustId) {
		this.payeeCustId = payeeCustId;
	}

	public String getPayeeAcctType() {
		return this.payeeAcctType;
	}

	public void setPayeeAcctType(String payeeAcctType) {
		this.payeeAcctType = payeeAcctType;
	}

	public String getPayeeCustName() {
		return this.payeeCustName;
	}

	public void setPayeeCustName(String payeeCustName) {
		this.payeeCustName = payeeCustName;
	}

	public String getPayeeBankType() {
		return this.payeeBankType;
	}

	public void setPayeeBankType(String payeeBankType) {
		this.payeeBankType = payeeBankType;
	}

	public String getPayeeBankCode() {
		return this.payeeBankCode;
	}

	public void setPayeeBankCode(String payeeBankCode) {
		this.payeeBankCode = payeeBankCode;
	}

	public String getPayeeBankName() {
		return this.payeeBankName;
	}

	public void setPayeeBankName(String payeeBankName) {
		this.payeeBankName = payeeBankName;
	}

	public String getPayeeBankArea() {
		return this.payeeBankArea;
	}

	public void setPayeeBankArea(String payeeBankArea) {
		this.payeeBankArea = payeeBankArea;
	}

	public String getPayeeBankAcctNo() {
		return this.payeeBankAcctNo;
	}

	public void setPayeeBankAcctNo(String payeeBankAcctNo) {
		this.payeeBankAcctNo = payeeBankAcctNo;
	}

	public String getPayeeBankAcctName() {
		return this.payeeBankAcctName;
	}

	public void setPayeeBankAcctName(String payeeBankAcctName) {
		this.payeeBankAcctName = payeeBankAcctName;
	}

	public String getEmergencyDegree() {
		return this.emergencyDegree;
	}

	public void setEmergencyDegree(String emergencyDegree) {
		this.emergencyDegree = emergencyDegree;
	}

	public String getIsGuarantee() {
		return this.isGuarantee;
	}

	public void setIsGuarantee(String isGuarantee) {
		this.isGuarantee = isGuarantee;
	}

	public String getGuaranteeState() {
		return this.guaranteeState;
	}

	public void setGuaranteeState(String guaranteeState) {
		this.guaranteeState = guaranteeState;
	}

	public String getGuaranteeCoreReturnCode() {
		return this.guaranteeCoreReturnCode;
	}

	public void setGuaranteeCoreReturnCode(String guaranteeCoreReturnCode) {
		this.guaranteeCoreReturnCode = guaranteeCoreReturnCode;
	}

	public String getGuaranteeCoreReturnMsg() {
		return this.guaranteeCoreReturnMsg;
	}

	public void setGuaranteeCoreReturnMsg(String guaranteeCoreReturnMsg) {
		this.guaranteeCoreReturnMsg = guaranteeCoreReturnMsg;
	}

	public String getOpTerm() {
		return this.opTerm;
	}

	public void setOpTerm(String opTerm) {
		this.opTerm = opTerm;
	}

	public String getPgUrl() {
		return this.pgUrl;
	}

	public void setPgUrl(String pgUrl) {
		this.pgUrl = pgUrl;
	}

	public String getBgUrl() {
		return this.bgUrl;
	}

	public void setBgUrl(String bgUrl) {
		this.bgUrl = bgUrl;
	}

	public String getDrawbackOrderId() {
		return this.drawbackOrderId;
	}

	public void setDrawbackOrderId(String drawbackOrderId) {
		this.drawbackOrderId = drawbackOrderId;
	}

	public String getCreateId() {
		return this.createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	public Date getCreateTime() {
		
		
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getModifyId() {
		return this.modifyId;
	}

	public void setModifyId(String modifyId) {
		this.modifyId = modifyId;
	}

	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getCoreSn() {
		return coreSn;
	}

	public void setCoreSn(String coreSn) {
		this.coreSn = coreSn;
	}

	public String getPayerAcctId() {
		return payerAcctId;
	}

	public void setPayerAcctId(String payerAcctId) {
		this.payerAcctId = payerAcctId;
	}

	public String getPayeeAcctId() {
		return payeeAcctId;
	}

	public void setPayeeAcctId(String payeeAcctId) {
		this.payeeAcctId = payeeAcctId;
	}
	
}
