package com.qifenqian.bms.meeting.winShow.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BasePrizeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BasePrizeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrizeIdIsNull() {
            addCriterion("prize_id is null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIsNotNull() {
            addCriterion("prize_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdEqualTo(Integer value) {
            addCriterion("prize_id =", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotEqualTo(Integer value) {
            addCriterion("prize_id <>", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThan(Integer value) {
            addCriterion("prize_id >", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_id >=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThan(Integer value) {
            addCriterion("prize_id <", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThanOrEqualTo(Integer value) {
            addCriterion("prize_id <=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIn(List<Integer> values) {
            addCriterion("prize_id in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotIn(List<Integer> values) {
            addCriterion("prize_id not in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdBetween(Integer value1, Integer value2) {
            addCriterion("prize_id between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_id not between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeNoIsNull() {
            addCriterion("prize_no is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNoIsNotNull() {
            addCriterion("prize_no is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNoEqualTo(String value) {
            addCriterion("prize_no =", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoNotEqualTo(String value) {
            addCriterion("prize_no <>", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoGreaterThan(String value) {
            addCriterion("prize_no >", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoGreaterThanOrEqualTo(String value) {
            addCriterion("prize_no >=", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoLessThan(String value) {
            addCriterion("prize_no <", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoLessThanOrEqualTo(String value) {
            addCriterion("prize_no <=", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoLike(String value) {
            addCriterion("prize_no like", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoNotLike(String value) {
            addCriterion("prize_no not like", value, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoIn(List<String> values) {
            addCriterion("prize_no in", values, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoNotIn(List<String> values) {
            addCriterion("prize_no not in", values, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoBetween(String value1, String value2) {
            addCriterion("prize_no between", value1, value2, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andPrizeNoNotBetween(String value1, String value2) {
            addCriterion("prize_no not between", value1, value2, "prizeNo");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("activity_id is null");
            return (Criteria) this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andActivityIdEqualTo(Integer value) {
            addCriterion("activity_id =", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotEqualTo(Integer value) {
            addCriterion("activity_id <>", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThan(Integer value) {
            addCriterion("activity_id >", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("activity_id >=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThan(Integer value) {
            addCriterion("activity_id <", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Integer value) {
            addCriterion("activity_id <=", value, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdIn(List<Integer> values) {
            addCriterion("activity_id in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotIn(List<Integer> values) {
            addCriterion("activity_id not in", values, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdBetween(Integer value1, Integer value2) {
            addCriterion("activity_id between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andActivityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("activity_id not between", value1, value2, "activityId");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeIsNull() {
            addCriterion("prize_code is null");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeIsNotNull() {
            addCriterion("prize_code is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeEqualTo(String value) {
            addCriterion("prize_code =", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeNotEqualTo(String value) {
            addCriterion("prize_code <>", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeGreaterThan(String value) {
            addCriterion("prize_code >", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("prize_code >=", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeLessThan(String value) {
            addCriterion("prize_code <", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeLessThanOrEqualTo(String value) {
            addCriterion("prize_code <=", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeLike(String value) {
            addCriterion("prize_code like", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeNotLike(String value) {
            addCriterion("prize_code not like", value, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeIn(List<String> values) {
            addCriterion("prize_code in", values, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeNotIn(List<String> values) {
            addCriterion("prize_code not in", values, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeBetween(String value1, String value2) {
            addCriterion("prize_code between", value1, value2, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeCodeNotBetween(String value1, String value2) {
            addCriterion("prize_code not between", value1, value2, "prizeCode");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNull() {
            addCriterion("prize_name is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNotNull() {
            addCriterion("prize_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameEqualTo(String value) {
            addCriterion("prize_name =", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotEqualTo(String value) {
            addCriterion("prize_name <>", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThan(String value) {
            addCriterion("prize_name >", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThanOrEqualTo(String value) {
            addCriterion("prize_name >=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThan(String value) {
            addCriterion("prize_name <", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThanOrEqualTo(String value) {
            addCriterion("prize_name <=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLike(String value) {
            addCriterion("prize_name like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotLike(String value) {
            addCriterion("prize_name not like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIn(List<String> values) {
            addCriterion("prize_name in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotIn(List<String> values) {
            addCriterion("prize_name not in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameBetween(String value1, String value2) {
            addCriterion("prize_name between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotBetween(String value1, String value2) {
            addCriterion("prize_name not between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIsNull() {
            addCriterion("prize_type is null");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIsNotNull() {
            addCriterion("prize_type is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeEqualTo(String value) {
            addCriterion("prize_type =", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeNotEqualTo(String value) {
            addCriterion("prize_type <>", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeGreaterThan(String value) {
            addCriterion("prize_type >", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("prize_type >=", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeLessThan(String value) {
            addCriterion("prize_type <", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeLessThanOrEqualTo(String value) {
            addCriterion("prize_type <=", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeLike(String value) {
            addCriterion("prize_type like", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeNotLike(String value) {
            addCriterion("prize_type not like", value, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIn(List<String> values) {
            addCriterion("prize_type in", values, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeNotIn(List<String> values) {
            addCriterion("prize_type not in", values, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeBetween(String value1, String value2) {
            addCriterion("prize_type between", value1, value2, "prizeType");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeNotBetween(String value1, String value2) {
            addCriterion("prize_type not between", value1, value2, "prizeType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeIsNull() {
            addCriterion("overall_control_type is null");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeIsNotNull() {
            addCriterion("overall_control_type is not null");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeEqualTo(String value) {
            addCriterion("overall_control_type =", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeNotEqualTo(String value) {
            addCriterion("overall_control_type <>", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeGreaterThan(String value) {
            addCriterion("overall_control_type >", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeGreaterThanOrEqualTo(String value) {
            addCriterion("overall_control_type >=", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeLessThan(String value) {
            addCriterion("overall_control_type <", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeLessThanOrEqualTo(String value) {
            addCriterion("overall_control_type <=", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeLike(String value) {
            addCriterion("overall_control_type like", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeNotLike(String value) {
            addCriterion("overall_control_type not like", value, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeIn(List<String> values) {
            addCriterion("overall_control_type in", values, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeNotIn(List<String> values) {
            addCriterion("overall_control_type not in", values, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeBetween(String value1, String value2) {
            addCriterion("overall_control_type between", value1, value2, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andOverallControlTypeNotBetween(String value1, String value2) {
            addCriterion("overall_control_type not between", value1, value2, "overallControlType");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberIsNull() {
            addCriterion("quota_number is null");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberIsNotNull() {
            addCriterion("quota_number is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberEqualTo(Integer value) {
            addCriterion("quota_number =", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberNotEqualTo(Integer value) {
            addCriterion("quota_number <>", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberGreaterThan(Integer value) {
            addCriterion("quota_number >", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("quota_number >=", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberLessThan(Integer value) {
            addCriterion("quota_number <", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberLessThanOrEqualTo(Integer value) {
            addCriterion("quota_number <=", value, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberIn(List<Integer> values) {
            addCriterion("quota_number in", values, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberNotIn(List<Integer> values) {
            addCriterion("quota_number not in", values, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberBetween(Integer value1, Integer value2) {
            addCriterion("quota_number between", value1, value2, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("quota_number not between", value1, value2, "quotaNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberIsNull() {
            addCriterion("win_number is null");
            return (Criteria) this;
        }

        public Criteria andWinNumberIsNotNull() {
            addCriterion("win_number is not null");
            return (Criteria) this;
        }

        public Criteria andWinNumberEqualTo(Integer value) {
            addCriterion("win_number =", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberNotEqualTo(Integer value) {
            addCriterion("win_number <>", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberGreaterThan(Integer value) {
            addCriterion("win_number >", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_number >=", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberLessThan(Integer value) {
            addCriterion("win_number <", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberLessThanOrEqualTo(Integer value) {
            addCriterion("win_number <=", value, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberIn(List<Integer> values) {
            addCriterion("win_number in", values, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberNotIn(List<Integer> values) {
            addCriterion("win_number not in", values, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberBetween(Integer value1, Integer value2) {
            addCriterion("win_number between", value1, value2, "winNumber");
            return (Criteria) this;
        }

        public Criteria andWinNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("win_number not between", value1, value2, "winNumber");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountIsNull() {
            addCriterion("quota_amount is null");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountIsNotNull() {
            addCriterion("quota_amount is not null");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountEqualTo(BigDecimal value) {
            addCriterion("quota_amount =", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountNotEqualTo(BigDecimal value) {
            addCriterion("quota_amount <>", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountGreaterThan(BigDecimal value) {
            addCriterion("quota_amount >", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("quota_amount >=", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountLessThan(BigDecimal value) {
            addCriterion("quota_amount <", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("quota_amount <=", value, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountIn(List<BigDecimal> values) {
            addCriterion("quota_amount in", values, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountNotIn(List<BigDecimal> values) {
            addCriterion("quota_amount not in", values, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quota_amount between", value1, value2, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andQuotaAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quota_amount not between", value1, value2, "quotaAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountIsNull() {
            addCriterion("win_amount is null");
            return (Criteria) this;
        }

        public Criteria andWinAmountIsNotNull() {
            addCriterion("win_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWinAmountEqualTo(BigDecimal value) {
            addCriterion("win_amount =", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotEqualTo(BigDecimal value) {
            addCriterion("win_amount <>", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountGreaterThan(BigDecimal value) {
            addCriterion("win_amount >", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("win_amount >=", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountLessThan(BigDecimal value) {
            addCriterion("win_amount <", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("win_amount <=", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountIn(List<BigDecimal> values) {
            addCriterion("win_amount in", values, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotIn(List<BigDecimal> values) {
            addCriterion("win_amount not in", values, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("win_amount between", value1, value2, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("win_amount not between", value1, value2, "winAmount");
            return (Criteria) this;
        }

        public Criteria andOddsFactorIsNull() {
            addCriterion("odds_factor is null");
            return (Criteria) this;
        }

        public Criteria andOddsFactorIsNotNull() {
            addCriterion("odds_factor is not null");
            return (Criteria) this;
        }

        public Criteria andOddsFactorEqualTo(Integer value) {
            addCriterion("odds_factor =", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorNotEqualTo(Integer value) {
            addCriterion("odds_factor <>", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorGreaterThan(Integer value) {
            addCriterion("odds_factor >", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorGreaterThanOrEqualTo(Integer value) {
            addCriterion("odds_factor >=", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorLessThan(Integer value) {
            addCriterion("odds_factor <", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorLessThanOrEqualTo(Integer value) {
            addCriterion("odds_factor <=", value, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorIn(List<Integer> values) {
            addCriterion("odds_factor in", values, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorNotIn(List<Integer> values) {
            addCriterion("odds_factor not in", values, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorBetween(Integer value1, Integer value2) {
            addCriterion("odds_factor between", value1, value2, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andOddsFactorNotBetween(Integer value1, Integer value2) {
            addCriterion("odds_factor not between", value1, value2, "oddsFactor");
            return (Criteria) this;
        }

        public Criteria andAmountTypeIsNull() {
            addCriterion("amount_type is null");
            return (Criteria) this;
        }

        public Criteria andAmountTypeIsNotNull() {
            addCriterion("amount_type is not null");
            return (Criteria) this;
        }

        public Criteria andAmountTypeEqualTo(String value) {
            addCriterion("amount_type =", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeNotEqualTo(String value) {
            addCriterion("amount_type <>", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeGreaterThan(String value) {
            addCriterion("amount_type >", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("amount_type >=", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeLessThan(String value) {
            addCriterion("amount_type <", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeLessThanOrEqualTo(String value) {
            addCriterion("amount_type <=", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeLike(String value) {
            addCriterion("amount_type like", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeNotLike(String value) {
            addCriterion("amount_type not like", value, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeIn(List<String> values) {
            addCriterion("amount_type in", values, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeNotIn(List<String> values) {
            addCriterion("amount_type not in", values, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeBetween(String value1, String value2) {
            addCriterion("amount_type between", value1, value2, "amountType");
            return (Criteria) this;
        }

        public Criteria andAmountTypeNotBetween(String value1, String value2) {
            addCriterion("amount_type not between", value1, value2, "amountType");
            return (Criteria) this;
        }

        public Criteria andFixedAmountIsNull() {
            addCriterion("fixed_amount is null");
            return (Criteria) this;
        }

        public Criteria andFixedAmountIsNotNull() {
            addCriterion("fixed_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFixedAmountEqualTo(BigDecimal value) {
            addCriterion("fixed_amount =", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountNotEqualTo(BigDecimal value) {
            addCriterion("fixed_amount <>", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountGreaterThan(BigDecimal value) {
            addCriterion("fixed_amount >", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fixed_amount >=", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountLessThan(BigDecimal value) {
            addCriterion("fixed_amount <", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fixed_amount <=", value, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountIn(List<BigDecimal> values) {
            addCriterion("fixed_amount in", values, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountNotIn(List<BigDecimal> values) {
            addCriterion("fixed_amount not in", values, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fixed_amount between", value1, value2, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andFixedAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fixed_amount not between", value1, value2, "fixedAmount");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinIsNull() {
            addCriterion("random_amount_min is null");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinIsNotNull() {
            addCriterion("random_amount_min is not null");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinEqualTo(BigDecimal value) {
            addCriterion("random_amount_min =", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinNotEqualTo(BigDecimal value) {
            addCriterion("random_amount_min <>", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinGreaterThan(BigDecimal value) {
            addCriterion("random_amount_min >", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("random_amount_min >=", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinLessThan(BigDecimal value) {
            addCriterion("random_amount_min <", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("random_amount_min <=", value, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinIn(List<BigDecimal> values) {
            addCriterion("random_amount_min in", values, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinNotIn(List<BigDecimal> values) {
            addCriterion("random_amount_min not in", values, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("random_amount_min between", value1, value2, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("random_amount_min not between", value1, value2, "randomAmountMin");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxIsNull() {
            addCriterion("random_amount_max is null");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxIsNotNull() {
            addCriterion("random_amount_max is not null");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxEqualTo(BigDecimal value) {
            addCriterion("random_amount_max =", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxNotEqualTo(BigDecimal value) {
            addCriterion("random_amount_max <>", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxGreaterThan(BigDecimal value) {
            addCriterion("random_amount_max >", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("random_amount_max >=", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxLessThan(BigDecimal value) {
            addCriterion("random_amount_max <", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("random_amount_max <=", value, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxIn(List<BigDecimal> values) {
            addCriterion("random_amount_max in", values, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxNotIn(List<BigDecimal> values) {
            addCriterion("random_amount_max not in", values, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("random_amount_max between", value1, value2, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andRandomAmountMaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("random_amount_max not between", value1, value2, "randomAmountMax");
            return (Criteria) this;
        }

        public Criteria andPrizeSortIsNull() {
            addCriterion("prize_sort is null");
            return (Criteria) this;
        }

        public Criteria andPrizeSortIsNotNull() {
            addCriterion("prize_sort is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeSortEqualTo(Integer value) {
            addCriterion("prize_sort =", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortNotEqualTo(Integer value) {
            addCriterion("prize_sort <>", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortGreaterThan(Integer value) {
            addCriterion("prize_sort >", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_sort >=", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortLessThan(Integer value) {
            addCriterion("prize_sort <", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortLessThanOrEqualTo(Integer value) {
            addCriterion("prize_sort <=", value, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortIn(List<Integer> values) {
            addCriterion("prize_sort in", values, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortNotIn(List<Integer> values) {
            addCriterion("prize_sort not in", values, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortBetween(Integer value1, Integer value2) {
            addCriterion("prize_sort between", value1, value2, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andPrizeSortNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_sort not between", value1, value2, "prizeSort");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursIsNull() {
            addCriterion("effective_hours is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursIsNotNull() {
            addCriterion("effective_hours is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursEqualTo(Integer value) {
            addCriterion("effective_hours =", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursNotEqualTo(Integer value) {
            addCriterion("effective_hours <>", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursGreaterThan(Integer value) {
            addCriterion("effective_hours >", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursGreaterThanOrEqualTo(Integer value) {
            addCriterion("effective_hours >=", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursLessThan(Integer value) {
            addCriterion("effective_hours <", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursLessThanOrEqualTo(Integer value) {
            addCriterion("effective_hours <=", value, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursIn(List<Integer> values) {
            addCriterion("effective_hours in", values, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursNotIn(List<Integer> values) {
            addCriterion("effective_hours not in", values, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursBetween(Integer value1, Integer value2) {
            addCriterion("effective_hours between", value1, value2, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andEffectiveHoursNotBetween(Integer value1, Integer value2) {
            addCriterion("effective_hours not between", value1, value2, "effectiveHours");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinIsNull() {
            addCriterion("is_repeat_win is null");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinIsNotNull() {
            addCriterion("is_repeat_win is not null");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinEqualTo(String value) {
            addCriterion("is_repeat_win =", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinNotEqualTo(String value) {
            addCriterion("is_repeat_win <>", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinGreaterThan(String value) {
            addCriterion("is_repeat_win >", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinGreaterThanOrEqualTo(String value) {
            addCriterion("is_repeat_win >=", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinLessThan(String value) {
            addCriterion("is_repeat_win <", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinLessThanOrEqualTo(String value) {
            addCriterion("is_repeat_win <=", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinLike(String value) {
            addCriterion("is_repeat_win like", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinNotLike(String value) {
            addCriterion("is_repeat_win not like", value, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinIn(List<String> values) {
            addCriterion("is_repeat_win in", values, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinNotIn(List<String> values) {
            addCriterion("is_repeat_win not in", values, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinBetween(String value1, String value2) {
            addCriterion("is_repeat_win between", value1, value2, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andIsRepeatWinNotBetween(String value1, String value2) {
            addCriterion("is_repeat_win not between", value1, value2, "isRepeatWin");
            return (Criteria) this;
        }

        public Criteria andCustScopeIsNull() {
            addCriterion("cust_scope is null");
            return (Criteria) this;
        }

        public Criteria andCustScopeIsNotNull() {
            addCriterion("cust_scope is not null");
            return (Criteria) this;
        }

        public Criteria andCustScopeEqualTo(String value) {
            addCriterion("cust_scope =", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeNotEqualTo(String value) {
            addCriterion("cust_scope <>", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeGreaterThan(String value) {
            addCriterion("cust_scope >", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeGreaterThanOrEqualTo(String value) {
            addCriterion("cust_scope >=", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeLessThan(String value) {
            addCriterion("cust_scope <", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeLessThanOrEqualTo(String value) {
            addCriterion("cust_scope <=", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeLike(String value) {
            addCriterion("cust_scope like", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeNotLike(String value) {
            addCriterion("cust_scope not like", value, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeIn(List<String> values) {
            addCriterion("cust_scope in", values, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeNotIn(List<String> values) {
            addCriterion("cust_scope not in", values, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeBetween(String value1, String value2) {
            addCriterion("cust_scope between", value1, value2, "custScope");
            return (Criteria) this;
        }

        public Criteria andCustScopeNotBetween(String value1, String value2) {
            addCriterion("cust_scope not between", value1, value2, "custScope");
            return (Criteria) this;
        }

        public Criteria andLimitSexIsNull() {
            addCriterion("limit_sex is null");
            return (Criteria) this;
        }

        public Criteria andLimitSexIsNotNull() {
            addCriterion("limit_sex is not null");
            return (Criteria) this;
        }

        public Criteria andLimitSexEqualTo(String value) {
            addCriterion("limit_sex =", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexNotEqualTo(String value) {
            addCriterion("limit_sex <>", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexGreaterThan(String value) {
            addCriterion("limit_sex >", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexGreaterThanOrEqualTo(String value) {
            addCriterion("limit_sex >=", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexLessThan(String value) {
            addCriterion("limit_sex <", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexLessThanOrEqualTo(String value) {
            addCriterion("limit_sex <=", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexLike(String value) {
            addCriterion("limit_sex like", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexNotLike(String value) {
            addCriterion("limit_sex not like", value, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexIn(List<String> values) {
            addCriterion("limit_sex in", values, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexNotIn(List<String> values) {
            addCriterion("limit_sex not in", values, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexBetween(String value1, String value2) {
            addCriterion("limit_sex between", value1, value2, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitSexNotBetween(String value1, String value2) {
            addCriterion("limit_sex not between", value1, value2, "limitSex");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartIsNull() {
            addCriterion("limit_register_date_start is null");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartIsNotNull() {
            addCriterion("limit_register_date_start is not null");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartEqualTo(Date value) {
            addCriterion("limit_register_date_start =", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartNotEqualTo(Date value) {
            addCriterion("limit_register_date_start <>", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartGreaterThan(Date value) {
            addCriterion("limit_register_date_start >", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartGreaterThanOrEqualTo(Date value) {
            addCriterion("limit_register_date_start >=", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartLessThan(Date value) {
            addCriterion("limit_register_date_start <", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartLessThanOrEqualTo(Date value) {
            addCriterion("limit_register_date_start <=", value, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartIn(List<Date> values) {
            addCriterion("limit_register_date_start in", values, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartNotIn(List<Date> values) {
            addCriterion("limit_register_date_start not in", values, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartBetween(Date value1, Date value2) {
            addCriterion("limit_register_date_start between", value1, value2, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateStartNotBetween(Date value1, Date value2) {
            addCriterion("limit_register_date_start not between", value1, value2, "limitRegisterDateStart");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndIsNull() {
            addCriterion("limit_register_date_end is null");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndIsNotNull() {
            addCriterion("limit_register_date_end is not null");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndEqualTo(Date value) {
            addCriterion("limit_register_date_end =", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndNotEqualTo(Date value) {
            addCriterion("limit_register_date_end <>", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndGreaterThan(Date value) {
            addCriterion("limit_register_date_end >", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndGreaterThanOrEqualTo(Date value) {
            addCriterion("limit_register_date_end >=", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndLessThan(Date value) {
            addCriterion("limit_register_date_end <", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndLessThanOrEqualTo(Date value) {
            addCriterion("limit_register_date_end <=", value, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndIn(List<Date> values) {
            addCriterion("limit_register_date_end in", values, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndNotIn(List<Date> values) {
            addCriterion("limit_register_date_end not in", values, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndBetween(Date value1, Date value2) {
            addCriterion("limit_register_date_end between", value1, value2, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andLimitRegisterDateEndNotBetween(Date value1, Date value2) {
            addCriterion("limit_register_date_end not between", value1, value2, "limitRegisterDateEnd");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNull() {
            addCriterion("inst_user is null");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNotNull() {
            addCriterion("inst_user is not null");
            return (Criteria) this;
        }

        public Criteria andInstUserEqualTo(String value) {
            addCriterion("inst_user =", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotEqualTo(String value) {
            addCriterion("inst_user <>", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThan(String value) {
            addCriterion("inst_user >", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThanOrEqualTo(String value) {
            addCriterion("inst_user >=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThan(String value) {
            addCriterion("inst_user <", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThanOrEqualTo(String value) {
            addCriterion("inst_user <=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLike(String value) {
            addCriterion("inst_user like", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotLike(String value) {
            addCriterion("inst_user not like", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserIn(List<String> values) {
            addCriterion("inst_user in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotIn(List<String> values) {
            addCriterion("inst_user not in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserBetween(String value1, String value2) {
            addCriterion("inst_user between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotBetween(String value1, String value2) {
            addCriterion("inst_user not between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNull() {
            addCriterion("inst_datetime is null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNotNull() {
            addCriterion("inst_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeEqualTo(Date value) {
            addCriterion("inst_datetime =", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotEqualTo(Date value) {
            addCriterion("inst_datetime <>", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThan(Date value) {
            addCriterion("inst_datetime >", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("inst_datetime >=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThan(Date value) {
            addCriterion("inst_datetime <", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("inst_datetime <=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIn(List<Date> values) {
            addCriterion("inst_datetime in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotIn(List<Date> values) {
            addCriterion("inst_datetime not in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeBetween(Date value1, Date value2) {
            addCriterion("inst_datetime between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("inst_datetime not between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNull() {
            addCriterion("lupd_user is null");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNotNull() {
            addCriterion("lupd_user is not null");
            return (Criteria) this;
        }

        public Criteria andLupdUserEqualTo(String value) {
            addCriterion("lupd_user =", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotEqualTo(String value) {
            addCriterion("lupd_user <>", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThan(String value) {
            addCriterion("lupd_user >", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThanOrEqualTo(String value) {
            addCriterion("lupd_user >=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThan(String value) {
            addCriterion("lupd_user <", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThanOrEqualTo(String value) {
            addCriterion("lupd_user <=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLike(String value) {
            addCriterion("lupd_user like", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotLike(String value) {
            addCriterion("lupd_user not like", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserIn(List<String> values) {
            addCriterion("lupd_user in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotIn(List<String> values) {
            addCriterion("lupd_user not in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserBetween(String value1, String value2) {
            addCriterion("lupd_user between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotBetween(String value1, String value2) {
            addCriterion("lupd_user not between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNull() {
            addCriterion("lupd_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNotNull() {
            addCriterion("lupd_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeEqualTo(Date value) {
            addCriterion("lupd_datetime =", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotEqualTo(Date value) {
            addCriterion("lupd_datetime <>", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThan(Date value) {
            addCriterion("lupd_datetime >", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime >=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThan(Date value) {
            addCriterion("lupd_datetime <", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime <=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIn(List<Date> values) {
            addCriterion("lupd_datetime in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotIn(List<Date> values) {
            addCriterion("lupd_datetime not in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime not between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 05 20:41:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}