package com.qifenqian.bms.meeting.winShow.bean;

import java.math.BigDecimal;
import java.util.Date;

public class BasePrize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer prizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_no
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String prizeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.activity_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_code
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String prizeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_name
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String prizeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.overall_control_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String overallControlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.quota_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer quotaNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.win_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer winNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.quota_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private BigDecimal quotaAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.win_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private BigDecimal winAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.odds_factor
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer oddsFactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.amount_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String amountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.fixed_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private BigDecimal fixedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.random_amount_min
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private BigDecimal randomAmountMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.random_amount_max
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private BigDecimal randomAmountMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.prize_sort
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer prizeSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.effective_hours
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Integer effectiveHours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.is_repeat_win
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String isRepeatWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.cust_scope
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String custScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.limit_sex
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String limitSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.limit_register_date_start
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Date limitRegisterDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.limit_register_date_end
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Date limitRegisterDateEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.memo
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.status
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.inst_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String instUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.inst_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Date instDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.lupd_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private String lupdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_prize.lupd_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    private Date lupdDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_id
     *
     * @return the value of base_prize.prize_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getPrizeId() {
        return prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_id
     *
     * @param prizeId the value for base_prize.prize_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeId(Integer prizeId) {
        this.prizeId = prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_no
     *
     * @return the value of base_prize.prize_no
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getPrizeNo() {
        return prizeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_no
     *
     * @param prizeNo the value for base_prize.prize_no
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeNo(String prizeNo) {
        this.prizeNo = prizeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.activity_id
     *
     * @return the value of base_prize.activity_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.activity_id
     *
     * @param activityId the value for base_prize.activity_id
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_code
     *
     * @return the value of base_prize.prize_code
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getPrizeCode() {
        return prizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_code
     *
     * @param prizeCode the value for base_prize.prize_code
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeCode(String prizeCode) {
        this.prizeCode = prizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_name
     *
     * @return the value of base_prize.prize_name
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_name
     *
     * @param prizeName the value for base_prize.prize_name
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_type
     *
     * @return the value of base_prize.prize_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getPrizeType() {
        return prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_type
     *
     * @param prizeType the value for base_prize.prize_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeType(String prizeType) {
        this.prizeType = prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.overall_control_type
     *
     * @return the value of base_prize.overall_control_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getOverallControlType() {
        return overallControlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.overall_control_type
     *
     * @param overallControlType the value for base_prize.overall_control_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setOverallControlType(String overallControlType) {
        this.overallControlType = overallControlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.quota_number
     *
     * @return the value of base_prize.quota_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getQuotaNumber() {
        return quotaNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.quota_number
     *
     * @param quotaNumber the value for base_prize.quota_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setQuotaNumber(Integer quotaNumber) {
        this.quotaNumber = quotaNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.win_number
     *
     * @return the value of base_prize.win_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getWinNumber() {
        return winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.win_number
     *
     * @param winNumber the value for base_prize.win_number
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setWinNumber(Integer winNumber) {
        this.winNumber = winNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.quota_amount
     *
     * @return the value of base_prize.quota_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BigDecimal getQuotaAmount() {
        return quotaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.quota_amount
     *
     * @param quotaAmount the value for base_prize.quota_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setQuotaAmount(BigDecimal quotaAmount) {
        this.quotaAmount = quotaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.win_amount
     *
     * @return the value of base_prize.win_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BigDecimal getWinAmount() {
        return winAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.win_amount
     *
     * @param winAmount the value for base_prize.win_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setWinAmount(BigDecimal winAmount) {
        this.winAmount = winAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.odds_factor
     *
     * @return the value of base_prize.odds_factor
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getOddsFactor() {
        return oddsFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.odds_factor
     *
     * @param oddsFactor the value for base_prize.odds_factor
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setOddsFactor(Integer oddsFactor) {
        this.oddsFactor = oddsFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.amount_type
     *
     * @return the value of base_prize.amount_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.amount_type
     *
     * @param amountType the value for base_prize.amount_type
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setAmountType(String amountType) {
        this.amountType = amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.fixed_amount
     *
     * @return the value of base_prize.fixed_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BigDecimal getFixedAmount() {
        return fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.fixed_amount
     *
     * @param fixedAmount the value for base_prize.fixed_amount
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setFixedAmount(BigDecimal fixedAmount) {
        this.fixedAmount = fixedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.random_amount_min
     *
     * @return the value of base_prize.random_amount_min
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BigDecimal getRandomAmountMin() {
        return randomAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.random_amount_min
     *
     * @param randomAmountMin the value for base_prize.random_amount_min
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setRandomAmountMin(BigDecimal randomAmountMin) {
        this.randomAmountMin = randomAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.random_amount_max
     *
     * @return the value of base_prize.random_amount_max
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public BigDecimal getRandomAmountMax() {
        return randomAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.random_amount_max
     *
     * @param randomAmountMax the value for base_prize.random_amount_max
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setRandomAmountMax(BigDecimal randomAmountMax) {
        this.randomAmountMax = randomAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.prize_sort
     *
     * @return the value of base_prize.prize_sort
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getPrizeSort() {
        return prizeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.prize_sort
     *
     * @param prizeSort the value for base_prize.prize_sort
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setPrizeSort(Integer prizeSort) {
        this.prizeSort = prizeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.effective_hours
     *
     * @return the value of base_prize.effective_hours
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Integer getEffectiveHours() {
        return effectiveHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.effective_hours
     *
     * @param effectiveHours the value for base_prize.effective_hours
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setEffectiveHours(Integer effectiveHours) {
        this.effectiveHours = effectiveHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.is_repeat_win
     *
     * @return the value of base_prize.is_repeat_win
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getIsRepeatWin() {
        return isRepeatWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.is_repeat_win
     *
     * @param isRepeatWin the value for base_prize.is_repeat_win
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setIsRepeatWin(String isRepeatWin) {
        this.isRepeatWin = isRepeatWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.cust_scope
     *
     * @return the value of base_prize.cust_scope
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getCustScope() {
        return custScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.cust_scope
     *
     * @param custScope the value for base_prize.cust_scope
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setCustScope(String custScope) {
        this.custScope = custScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.limit_sex
     *
     * @return the value of base_prize.limit_sex
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getLimitSex() {
        return limitSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.limit_sex
     *
     * @param limitSex the value for base_prize.limit_sex
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setLimitSex(String limitSex) {
        this.limitSex = limitSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.limit_register_date_start
     *
     * @return the value of base_prize.limit_register_date_start
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Date getLimitRegisterDateStart() {
        return limitRegisterDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.limit_register_date_start
     *
     * @param limitRegisterDateStart the value for base_prize.limit_register_date_start
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setLimitRegisterDateStart(Date limitRegisterDateStart) {
        this.limitRegisterDateStart = limitRegisterDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.limit_register_date_end
     *
     * @return the value of base_prize.limit_register_date_end
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Date getLimitRegisterDateEnd() {
        return limitRegisterDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.limit_register_date_end
     *
     * @param limitRegisterDateEnd the value for base_prize.limit_register_date_end
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setLimitRegisterDateEnd(Date limitRegisterDateEnd) {
        this.limitRegisterDateEnd = limitRegisterDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.memo
     *
     * @return the value of base_prize.memo
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.memo
     *
     * @param memo the value for base_prize.memo
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.status
     *
     * @return the value of base_prize.status
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.status
     *
     * @param status the value for base_prize.status
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.inst_user
     *
     * @return the value of base_prize.inst_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getInstUser() {
        return instUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.inst_user
     *
     * @param instUser the value for base_prize.inst_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setInstUser(String instUser) {
        this.instUser = instUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.inst_datetime
     *
     * @return the value of base_prize.inst_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Date getInstDatetime() {
        return instDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.inst_datetime
     *
     * @param instDatetime the value for base_prize.inst_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setInstDatetime(Date instDatetime) {
        this.instDatetime = instDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.lupd_user
     *
     * @return the value of base_prize.lupd_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public String getLupdUser() {
        return lupdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.lupd_user
     *
     * @param lupdUser the value for base_prize.lupd_user
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setLupdUser(String lupdUser) {
        this.lupdUser = lupdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_prize.lupd_datetime
     *
     * @return the value of base_prize.lupd_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public Date getLupdDatetime() {
        return lupdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_prize.lupd_datetime
     *
     * @param lupdDatetime the value for base_prize.lupd_datetime
     *
     * @mbggenerated Tue Jan 05 20:41:06 CST 2016
     */
    public void setLupdDatetime(Date lupdDatetime) {
        this.lupdDatetime = lupdDatetime;
    }
}