package com.qifenqian.bms.meeting.winShow.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BasePrizeWinExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public BasePrizeWinExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWinIdIsNull() {
            addCriterion("win_id is null");
            return (Criteria) this;
        }

        public Criteria andWinIdIsNotNull() {
            addCriterion("win_id is not null");
            return (Criteria) this;
        }

        public Criteria andWinIdEqualTo(Integer value) {
            addCriterion("win_id =", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdNotEqualTo(Integer value) {
            addCriterion("win_id <>", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdGreaterThan(Integer value) {
            addCriterion("win_id >", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("win_id >=", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdLessThan(Integer value) {
            addCriterion("win_id <", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdLessThanOrEqualTo(Integer value) {
            addCriterion("win_id <=", value, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdIn(List<Integer> values) {
            addCriterion("win_id in", values, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdNotIn(List<Integer> values) {
            addCriterion("win_id not in", values, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdBetween(Integer value1, Integer value2) {
            addCriterion("win_id between", value1, value2, "winId");
            return (Criteria) this;
        }

        public Criteria andWinIdNotBetween(Integer value1, Integer value2) {
            addCriterion("win_id not between", value1, value2, "winId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIsNull() {
            addCriterion("prize_id is null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIsNotNull() {
            addCriterion("prize_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdEqualTo(Integer value) {
            addCriterion("prize_id =", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotEqualTo(Integer value) {
            addCriterion("prize_id <>", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThan(Integer value) {
            addCriterion("prize_id >", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_id >=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThan(Integer value) {
            addCriterion("prize_id <", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThanOrEqualTo(Integer value) {
            addCriterion("prize_id <=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIn(List<Integer> values) {
            addCriterion("prize_id in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotIn(List<Integer> values) {
            addCriterion("prize_id not in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdBetween(Integer value1, Integer value2) {
            addCriterion("prize_id between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_id not between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdIsNull() {
            addCriterion("win_cust_id is null");
            return (Criteria) this;
        }

        public Criteria andWinCustIdIsNotNull() {
            addCriterion("win_cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andWinCustIdEqualTo(String value) {
            addCriterion("win_cust_id =", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdNotEqualTo(String value) {
            addCriterion("win_cust_id <>", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdGreaterThan(String value) {
            addCriterion("win_cust_id >", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("win_cust_id >=", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdLessThan(String value) {
            addCriterion("win_cust_id <", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdLessThanOrEqualTo(String value) {
            addCriterion("win_cust_id <=", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdLike(String value) {
            addCriterion("win_cust_id like", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdNotLike(String value) {
            addCriterion("win_cust_id not like", value, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdIn(List<String> values) {
            addCriterion("win_cust_id in", values, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdNotIn(List<String> values) {
            addCriterion("win_cust_id not in", values, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdBetween(String value1, String value2) {
            addCriterion("win_cust_id between", value1, value2, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustIdNotBetween(String value1, String value2) {
            addCriterion("win_cust_id not between", value1, value2, "winCustId");
            return (Criteria) this;
        }

        public Criteria andWinCustNameIsNull() {
            addCriterion("win_cust_name is null");
            return (Criteria) this;
        }

        public Criteria andWinCustNameIsNotNull() {
            addCriterion("win_cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andWinCustNameEqualTo(String value) {
            addCriterion("win_cust_name =", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameNotEqualTo(String value) {
            addCriterion("win_cust_name <>", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameGreaterThan(String value) {
            addCriterion("win_cust_name >", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("win_cust_name >=", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameLessThan(String value) {
            addCriterion("win_cust_name <", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameLessThanOrEqualTo(String value) {
            addCriterion("win_cust_name <=", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameLike(String value) {
            addCriterion("win_cust_name like", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameNotLike(String value) {
            addCriterion("win_cust_name not like", value, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameIn(List<String> values) {
            addCriterion("win_cust_name in", values, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameNotIn(List<String> values) {
            addCriterion("win_cust_name not in", values, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameBetween(String value1, String value2) {
            addCriterion("win_cust_name between", value1, value2, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustNameNotBetween(String value1, String value2) {
            addCriterion("win_cust_name not between", value1, value2, "winCustName");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneIsNull() {
            addCriterion("win_cust_phone is null");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneIsNotNull() {
            addCriterion("win_cust_phone is not null");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneEqualTo(String value) {
            addCriterion("win_cust_phone =", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneNotEqualTo(String value) {
            addCriterion("win_cust_phone <>", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneGreaterThan(String value) {
            addCriterion("win_cust_phone >", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("win_cust_phone >=", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneLessThan(String value) {
            addCriterion("win_cust_phone <", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneLessThanOrEqualTo(String value) {
            addCriterion("win_cust_phone <=", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneLike(String value) {
            addCriterion("win_cust_phone like", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneNotLike(String value) {
            addCriterion("win_cust_phone not like", value, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneIn(List<String> values) {
            addCriterion("win_cust_phone in", values, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneNotIn(List<String> values) {
            addCriterion("win_cust_phone not in", values, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneBetween(String value1, String value2) {
            addCriterion("win_cust_phone between", value1, value2, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinCustPhoneNotBetween(String value1, String value2) {
            addCriterion("win_cust_phone not between", value1, value2, "winCustPhone");
            return (Criteria) this;
        }

        public Criteria andWinAmountIsNull() {
            addCriterion("win_amount is null");
            return (Criteria) this;
        }

        public Criteria andWinAmountIsNotNull() {
            addCriterion("win_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWinAmountEqualTo(BigDecimal value) {
            addCriterion("win_amount =", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotEqualTo(BigDecimal value) {
            addCriterion("win_amount <>", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountGreaterThan(BigDecimal value) {
            addCriterion("win_amount >", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("win_amount >=", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountLessThan(BigDecimal value) {
            addCriterion("win_amount <", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("win_amount <=", value, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountIn(List<BigDecimal> values) {
            addCriterion("win_amount in", values, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotIn(List<BigDecimal> values) {
            addCriterion("win_amount not in", values, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("win_amount between", value1, value2, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("win_amount not between", value1, value2, "winAmount");
            return (Criteria) this;
        }

        public Criteria andWinMarkIsNull() {
            addCriterion("win_mark is null");
            return (Criteria) this;
        }

        public Criteria andWinMarkIsNotNull() {
            addCriterion("win_mark is not null");
            return (Criteria) this;
        }

        public Criteria andWinMarkEqualTo(String value) {
            addCriterion("win_mark =", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkNotEqualTo(String value) {
            addCriterion("win_mark <>", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkGreaterThan(String value) {
            addCriterion("win_mark >", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkGreaterThanOrEqualTo(String value) {
            addCriterion("win_mark >=", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkLessThan(String value) {
            addCriterion("win_mark <", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkLessThanOrEqualTo(String value) {
            addCriterion("win_mark <=", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkLike(String value) {
            addCriterion("win_mark like", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkNotLike(String value) {
            addCriterion("win_mark not like", value, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkIn(List<String> values) {
            addCriterion("win_mark in", values, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkNotIn(List<String> values) {
            addCriterion("win_mark not in", values, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkBetween(String value1, String value2) {
            addCriterion("win_mark between", value1, value2, "winMark");
            return (Criteria) this;
        }

        public Criteria andWinMarkNotBetween(String value1, String value2) {
            addCriterion("win_mark not between", value1, value2, "winMark");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineIsNull() {
            addCriterion("effective_deadline is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineIsNotNull() {
            addCriterion("effective_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineEqualTo(Date value) {
            addCriterion("effective_deadline =", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineNotEqualTo(Date value) {
            addCriterion("effective_deadline <>", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineGreaterThan(Date value) {
            addCriterion("effective_deadline >", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("effective_deadline >=", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineLessThan(Date value) {
            addCriterion("effective_deadline <", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("effective_deadline <=", value, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineIn(List<Date> values) {
            addCriterion("effective_deadline in", values, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineNotIn(List<Date> values) {
            addCriterion("effective_deadline not in", values, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineBetween(Date value1, Date value2) {
            addCriterion("effective_deadline between", value1, value2, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andEffectiveDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("effective_deadline not between", value1, value2, "effectiveDeadline");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNull() {
            addCriterion("inst_user is null");
            return (Criteria) this;
        }

        public Criteria andInstUserIsNotNull() {
            addCriterion("inst_user is not null");
            return (Criteria) this;
        }

        public Criteria andInstUserEqualTo(String value) {
            addCriterion("inst_user =", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotEqualTo(String value) {
            addCriterion("inst_user <>", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThan(String value) {
            addCriterion("inst_user >", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserGreaterThanOrEqualTo(String value) {
            addCriterion("inst_user >=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThan(String value) {
            addCriterion("inst_user <", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLessThanOrEqualTo(String value) {
            addCriterion("inst_user <=", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserLike(String value) {
            addCriterion("inst_user like", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotLike(String value) {
            addCriterion("inst_user not like", value, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserIn(List<String> values) {
            addCriterion("inst_user in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotIn(List<String> values) {
            addCriterion("inst_user not in", values, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserBetween(String value1, String value2) {
            addCriterion("inst_user between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstUserNotBetween(String value1, String value2) {
            addCriterion("inst_user not between", value1, value2, "instUser");
            return (Criteria) this;
        }

        public Criteria andInstDateIsNull() {
            addCriterion("inst_date is null");
            return (Criteria) this;
        }

        public Criteria andInstDateIsNotNull() {
            addCriterion("inst_date is not null");
            return (Criteria) this;
        }

        public Criteria andInstDateEqualTo(String value) {
            addCriterion("inst_date =", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateNotEqualTo(String value) {
            addCriterion("inst_date <>", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateGreaterThan(String value) {
            addCriterion("inst_date >", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateGreaterThanOrEqualTo(String value) {
            addCriterion("inst_date >=", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateLessThan(String value) {
            addCriterion("inst_date <", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateLessThanOrEqualTo(String value) {
            addCriterion("inst_date <=", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateLike(String value) {
            addCriterion("inst_date like", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateNotLike(String value) {
            addCriterion("inst_date not like", value, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateIn(List<String> values) {
            addCriterion("inst_date in", values, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateNotIn(List<String> values) {
            addCriterion("inst_date not in", values, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateBetween(String value1, String value2) {
            addCriterion("inst_date between", value1, value2, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDateNotBetween(String value1, String value2) {
            addCriterion("inst_date not between", value1, value2, "instDate");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNull() {
            addCriterion("inst_datetime is null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIsNotNull() {
            addCriterion("inst_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeEqualTo(Date value) {
            addCriterion("inst_datetime =", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotEqualTo(Date value) {
            addCriterion("inst_datetime <>", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThan(Date value) {
            addCriterion("inst_datetime >", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("inst_datetime >=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThan(Date value) {
            addCriterion("inst_datetime <", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("inst_datetime <=", value, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeIn(List<Date> values) {
            addCriterion("inst_datetime in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotIn(List<Date> values) {
            addCriterion("inst_datetime not in", values, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeBetween(Date value1, Date value2) {
            addCriterion("inst_datetime between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andInstDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("inst_datetime not between", value1, value2, "instDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNull() {
            addCriterion("lupd_user is null");
            return (Criteria) this;
        }

        public Criteria andLupdUserIsNotNull() {
            addCriterion("lupd_user is not null");
            return (Criteria) this;
        }

        public Criteria andLupdUserEqualTo(String value) {
            addCriterion("lupd_user =", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotEqualTo(String value) {
            addCriterion("lupd_user <>", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThan(String value) {
            addCriterion("lupd_user >", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserGreaterThanOrEqualTo(String value) {
            addCriterion("lupd_user >=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThan(String value) {
            addCriterion("lupd_user <", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLessThanOrEqualTo(String value) {
            addCriterion("lupd_user <=", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserLike(String value) {
            addCriterion("lupd_user like", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotLike(String value) {
            addCriterion("lupd_user not like", value, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserIn(List<String> values) {
            addCriterion("lupd_user in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotIn(List<String> values) {
            addCriterion("lupd_user not in", values, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserBetween(String value1, String value2) {
            addCriterion("lupd_user between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdUserNotBetween(String value1, String value2) {
            addCriterion("lupd_user not between", value1, value2, "lupdUser");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNull() {
            addCriterion("lupd_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIsNotNull() {
            addCriterion("lupd_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeEqualTo(Date value) {
            addCriterion("lupd_datetime =", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotEqualTo(Date value) {
            addCriterion("lupd_datetime <>", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThan(Date value) {
            addCriterion("lupd_datetime >", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime >=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThan(Date value) {
            addCriterion("lupd_datetime <", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lupd_datetime <=", value, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeIn(List<Date> values) {
            addCriterion("lupd_datetime in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotIn(List<Date> values) {
            addCriterion("lupd_datetime not in", values, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }

        public Criteria andLupdDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lupd_datetime not between", value1, value2, "lupdDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize_win
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 05 20:41:52 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_prize_win
     *
     * @mbggenerated Tue Jan 05 20:41:52 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}