app:
   service:
      version: 1.0.0
dubbo:
  application:
    name: service-provider
    qosEnable: false
  registry:
    address: zookeeper://172.16.30.5:2181?backup=172.16.30.70:2181,172.16.30.71:2181
    file: /data/dubbo/dubbo-service-provider.cache


images:
  relativePaths: /pic/**
  absolutePaths: /data/nfsshare/upload/picture
  uri: https://sp.qifenqian.com/
  relativePath: /pic/


spring:
  redis:
    host: 172.16.30.70
    port: 6379
    password: pass123
    jedis:
      pool:
        max-active: 66

wxauth:
  #填写公众号的APPID
  appid: wxce65746e62998dce
  #填写公众号的APPSECRET
  appsecret: 67c3aebf0e3e397df1fce595b837353b
  #这里的token要和微信公众号号网页填写的token一样
  token: ok_ok_token
swagger:
    enable: false